// wordDatabase.js
// ==========================================
// 🗂️ 雙版本字庫資料區 (三層：年級 -> 學期 -> 單元)
// ==========================================
const wordDatabase = [
    {
        grade: "七年級",
        semesters: [
            {
                semester: "114上",
                units: [
                    { unit: "K L1", words: "family,家人；家庭\nhusband,丈夫\nwife,妻子\nuncle,叔（伯）父；姑（姨）丈；舅舅\naunt,嬸嬸；伯母；姑（姨）媽；舅媽\ncousin,堂（表）兄弟姐妹\nson,兒子\ndaughter,女兒\nparent,雙親之一\nchild / children,孩子\nyoung,年輕的\nman / men,男人\nhandsome,英俊的\nour,我們的\nPE,體育\nreally,真地\nclassroom,教室\nsame,一樣的\nclass,班級；課程\nagain,再一次\nNice to meet you.,很高興認識你。\ntoo,也；太\nnews,消息；新聞\nproblem,問題\nstrict,嚴格的\njunior high school,國民中學\nwarm,溫暖的\nfarmer,農夫\ncook,廚師；煮\nnurse,護理師；護士\nbeautiful,漂亮的；美麗的\nwoman / women,女人\ndoctor,醫生\nsenior high school,高級中學\npet,寵物\ncute,可愛的\nnice,好的；好心的" }, 
                    { unit: "K L2", words: "monkey,猴子\nfox,狐狸\nsheep,綿羊\ntiger,老虎\nzebra,斑馬\nlion,獅子\nmouse / mice,老鼠\nbear,熊\nmovie theater,電影院\nChinese,中國的；中國人；中文\nanimal,動物\nsign,符號\nrat,大老鼠\nox / oxen,（公）牛\nrabbit,兔子\ndragon,龍\nsnake,蛇\nhorse,馬\ngoat,山羊\nrooster,公雞\nsmart,聰明的\nenergetic,充滿活力的\ntrue,真的；真實的\nno wonder,難怪\npeople,人們\nWhat about…?,……怎麼樣？\npeople person,人緣好的人\npicture,照片；圖畫\nelephant,大象\nor,或者\nsize,尺寸\ndifferent,不同的\nvery,很；非常\ntheir,牠們的；他們的\nmeter,公尺\nbut,但是\nonly,僅僅；只\nlifespan,壽命" },
                    { unit: "K L3", words: "living room,客廳\nbedroom,臥室\nbathroom,浴室\ndining room,飯廳\nbehind,在……後面\nin front of,在……前面\nbetween,在……中間\nnext to,在……旁邊\nnear,在……附近\nplease,請\nhouse,房子\nquiet,安靜的\nstyle,風格；款式\nidea,想法；點子\nlet’s...,我們一起……吧\nget,獲得\nsome,一些的；一些\ntool,工具\nsmartphone,智慧型手機\nstep,步驟；一步\nupload,上傳\nphoto,相片\nchoose,選擇\ntype,種類\ntheme,主題\nwait,等待\nexpensive,昂貴的\nwith,對……來說；和\nquestion,問題\nI see.,我了解了。\nsoft,柔軟的\nhard,硬的\nin fact,事實上\naround,圍繞；到處\nworld,世界\nkitchen,廚房\nbeside,在……旁邊\ice,冰\ninside,在……裡面；在室內\nblanket,毛毯" }, 
                    { unit: "K L4", words: "listen,聽\nvoice,聲音；歌喉\nstand up,站起來\nsit down,坐下\ntake a photo,拍照\nmake,製造\nany,任何（的）\nnoise,噪音\ncan’t,不能；不會；不可以\ntalk,講話\nnoisy,吵闹的\nlate,晚的；遲到的\nearly,早的；初期的\nsidewalk,人行道\nsong,歌曲\ncheck out,查看\ncross,跨越\nroad,道路\nwatch out,小心；注意\nreal,真的；真實的\nall the time,一直\nGuess what?,你猜怎麼著？\ntraffic lights,紅綠燈\nground,地面\ndesign,設計\nuser,使用者\ndownload,下載\nwarn,警告\noncoming,迎面而來的\ncrosswalk,斑馬線\nalso,而且；也\nthe USA,美國\nspecial,特別的\nlane,小路；小巷\nway,方式；方法；路\nother,其他的" },
                    { unit: "K L5", words: "week,星期\nMonday,星期一\nTuesday,星期二\nWednesday,星期三\nbasketball,籃球\nThursday,星期四\nFriday,星期五\nSaturday,星期六\nbirthday,生日\nparty,派對\nSunday,星期日\nday,日\nweekend,週末\nnoon,中午\nwake up,醒來\nlook for,尋找\nHurry up.,快一點。\nby the way,順帶一提\njoin,參加；加入\ngroup,團體\nchat,談話\ntonight,今晚\nmeeting,會議\np.m.,下午；晚上\nlife,生活\nprepare,準備\no’clock,……點鐘\neveryone / everybody,每個人；各位\na.m.,上午；凌晨\ncity,城市\nsay,說\nsun,太陽\nrise,上升\nshine,照耀；發光\ndinner,晚餐" }, 
                    { unit: "K L6", words: "gate,大門\nsports field,運動場；操場\nbasketball court,籃球場\nrestroom,廁所\nlibrary,圖書館\nplayground,遊樂場\nswing,秋千\nslide,滑梯\ngarden,花園\nseesaw,蹺蹺板\nbasket,籃子\nrest,休息\nshow... around,帶……參觀\nbuilding,建築物\ngym,體育館\nwork out,鍛鍊身體\nafter school,放學後\nlarge,大的；大量的\nclassmate,同班同學\nput,放置\nshelf,架子\noutside,在……外面；在室外\nworry,擔心\nwear,穿；戴\nstill,仍然\nfind,找到；發現\nfeet / foot,腳\nhungry,飢餓的\nsandwich,三明治\nfind one’s feet,適應新環境\nmeaning,意思；意義\nthink,想起；思考；認為\na lot of / lots of,許多的\nthing,事；物\nhowever,然而\nfriendly,友善的" },
                    { unit: "U L1", words: "handsome,英俊的\nnew,新的\nclassmate,同學\nyoung,年輕的\nwoman,女人\nvery,非常\nbeautiful,美麗的\ntoo,也\nNice to meet you.,很高興認識你。\ncousin,堂表兄弟姐妹\nreally,真地\nyear(s) old,⋯歲\nI see.,我知道了。\nsinger,歌手\noffice worker,上班族\nhousewife,家庭主婦\npolice officer,警察\nwriter,作家\nuncle,叔伯；舅舅\naunt,阿姨；姑姑\nwife,妻子\ndaughter,女兒\nhusband,丈夫\nson,兒子\ndear,親愛的\nfamily,家庭；家人\nelementary school,國小\njunior high school,國中\nbaby,嬰兒；年幼的" }, 
                    { unit: "U L2", words: "house,房子\nparents,父母親\nliving room,客廳\nwall,牆壁\npurple,紫色（的）\nfavorite,最喜愛（的）\ncolor,顏色\nkitchen,廚房\ndining room,飯廳\nbut,但是\ngray,灰色（的）\nbrown,棕色（的）\ncookie,餅乾\nmice,老鼠（複數）\nmaybe,可能\nsofa,沙發\nhungry,餓的\nnotebook,筆記本\nmarker,記號筆；彩色筆\nbrush,毛筆；筆刷\ngift,禮物\npencil case,鉛筆盒\nbathroom,浴室；廁所\ntable,桌子\nbedroom,臥室\nnear,在⋯附近\nbetween,在⋯之間\nbehind,在⋯後面\nin front of,在⋯前面\nspecial,特別的\ninside,在⋯裡面\nright,就\neach other,彼此；互相\nabove,在⋯上方；在上方\nenough,足夠（的）\nperson,人" },
                    { unit: "U L3", words: "guy,人；傢伙\nmagic,神奇的；魔法\nwith,用；和\ncan,可以；會\nmany,許多（的）\nplace,地方\nuse,使用\nsure,當然；確定的\nlet's...,讓我們一起⋯\ncareful,小心的\nmuseum,博物館\nHurry!,快點！\nplease,請；拜託\nwait,等待\nman,男人\nnow,現在\nor,或者\ntime,次；時間\nwake up,醒來；叫醒⋯\nclass,課；班級\nOh my!,天哪！\nsee,看見\nquiet,安靜的\nturn off,關掉\nsign,標誌\ntalk,說話\nfight,吵架；打架\nturn,（依次輪到的）機會\nfollow,遵守；跟隨\nrule,規則\nsafe,安全的\nwash,清洗\nhand,手\nafter class,下課後" }, 
                    { unit: "U L4", words: "music video,音樂影片\nband,樂團\ntake a look,看一看\nall,所有的\ncute,可愛的\ngreat,棒的\nfree,有空的\nweekend,週末\nSaturday,星期六\ntogether,一起\nready,準備好的\np.m.,下午；晚上\no'clock,⋯點鐘\nday,日；天\ntoday,今天\nFriday,星期五\nSunday,星期日\nMonday,星期一\nTuesday,星期二\nWednesday,星期三\nThursday,星期四\nweek,週；星期\na.m.,上午；凌晨\nstudy,研讀\nEnglish,英文\ntake a walk,散步\nmovie,電影\ntake a picture,拍照\nparty,派對；宴會\nreport,報導\npopular,受歡迎的\nfan,⋯迷\nshake hands,握手\neveryone,每個人\nsign,簽名" },
                    { unit: "U L5", words: "date,日期\nNovember,十一月\nfirst,第一（的）\nThanksgiving,感恩節\nimportant,重要的\nholiday,節日；假日\nwhen,何時\nfourth,第四（的）\nbirthday,生日\nalso,也；此外\nbefore,在⋯之前\naround,圍繞；在⋯附近\nHow about...?,那⋯呢？\nsecond,第二（的）\nnext,下一個的\nmonth,月份\nJanuary,一月\nFebruary,二月\nMarch,三月\nApril,四月\nMay,五月\nJune,六月\nJuly,七月\nAugust,八月\nSeptember,九月\nOctober,十月\nDecember,十二月\nNew Year's Eve,元旦前夕\nChristmas,聖誕節\nthird,第三（的）\nanimal,動物\ncow,牛；乳牛\nthink,想；認為\nlucky,幸運的\nonly,只是；唯一的\ndinner,晚餐" }, 
                    { unit: "U L6", words: "lion,獅子\nover there,在那裡\nking,國王\nsome,一些（的）\nelephant,大象\nso,如此地\nany,任何（的）\ntiger,老虎\nzebra,斑馬\nback,背；後面\nhelp,幫助；幫忙\nright,正確的\nmonkey,猴子\nfox,狐狸\nhorse,馬\nrat,老鼠\nbear,熊\nworld,世界\nexample,實例\nbug,蟲子\nfood,食物\nclean up,清理；打掃\nfull,飽的；滿的\nhealthy,健康的\nthanks to,幸虧；由於\nclean,乾淨的" }
                ]
            },
            {
                semester: "114下",
                units: [
                    { unit: "K L1", words: "get up,起床\nteeth / tooth,牙齒（複數形／單數形）\nface,臉\nexercise,運動\nbreakfast,早餐\nbath,泡澡；洗澡\nhomework,家庭作業\nbaseball,棒球\nsoccer,足球\nvideo game,電玩遊戲\npractice,練習\nevery,每一\nteam,隊伍\nknow,知道\nplayer,運動員；選手\ngrade,成績\ntest,考試\nstudy,研讀；研究\either,也（用於否定句）\nmust,一定；必須\nenjoy,享受\nthen,那麼；然後\nticket,票；券\ntogether,一起\nhow much,多少錢\nhundred,百\ndollar,元\nbadminton,羽毛球\ntennis,網球\nask,問；要求\nhappen,發生\nfast,快速的\nmove,移動；搬家\nhit,擊；打；襲擊\nfun,樂趣；有趣的\nwin,贏\nlose,輸掉（比賽）；失去\nside,邊；面\ntouch,接觸；觸碰\nlast,最後的；前一個的\npoint,得分；觀點" }, 
                    { unit: "K L2", words: "housework,家事\nmop,拖（地）；拖把\nfloor,地板；樓層\nclean,打掃；乾淨的\ntrash,垃圾\ndo the dishes,洗碗盤\nset,布置；設定\nstreet,街道\nmarket,巿場\ntown,城鎮\nanytime,任何時候\nseldom,很少\nalways,總是\nhabit,習慣\nnever,從不\nbreak,打破；休息\noften,時常\nsometimes,有時候\nsure,確定的；當然\nplace,地方\nusually,通常\ndirty,髒的\nmonth,月\nbelieve,相信\nonce,一次\ntwice,兩次\nterrible,可怕的；糟糕的\nhow often,多常\ncellphone,手機\nfollowing,下列事物（或人員）；下述的\nmay / might,可能；也許\nchange,改變\nmore,更多的\ngerm,細菌\ntoilet seat,馬桶座\nanswer,答案；回答\nfor example,舉例來說\nfree,空閒的；免費的\nfinger,手指\nkill,殺\ntime,次數\nwork,工作" },
                    { unit: "K L3", words: "January,一月\nFebruary,二月\nMarch,三月\nApril,四月\nMay,五月\nJune,六月\nJuly,七月\nAugust,八月\nSeptember,九月\nOctober,十月\nNovember,十一月\nDecember,十二月\nEaster,復活節\nHalloween,萬聖節前夕\nThanksgiving,感恩節\nChristmas,聖誕節\nholiday,節日；假期\nrace,賽跑；競賽\nwhose,誰的\nwhen,何時\nsecond,第二（的）；秒\ndate,日期；約會\nthird,第三（的）\naway,離……之遠；離開\nfirst,第一（的）；首先\nrunner,跑者\nover there,在那邊\ntake care of,照顧\nplay the role of,扮演……的角色\nletter,信件\ndear,親愛的\nbusy,忙碌的\nmiss,想念\neverything,一切事物\nlove,愛" }, 
                    { unit: "K L4", words: "food,食物\nbottle,瓶子\nwater,水；澆水\nbowl,碗\nrice,米；飯\nplate,盤子\nnoodle,麵條\npie,派\npiece,塊；片；張\nglass,玻璃杯；玻璃\ngram,公克\nkilogram,公斤\nsalt,鹽\nsugar,糖\na few,幾個；一些\na little,少量的；一點\ncan,（鐵、鋁）罐\npancake,鬆餅\nhelp,幫助\nhow many,多少（個）\ngive,給\nneed,需要\nflour,麵粉\nof course,當然\nwhich,哪一個\nenough,足夠的\nyummy,美味的\nteach,教\neasy,容易的\nhow much,多少\ndelicious,美味的\ndifficult,困難的\nadd,添加\nmix,混合\nheat,加熱；熱\npan,平底鍋\nbutter,奶油\nround,圓形的\nbatter,糊狀物\nuntil,直到……為止\nbrown,棕色（的）\nboth,兩者（……都）\nready,準備好的" },
                    { unit: "K L5", words: "science,科學\ncamp,營隊；露營\nvisit,造訪；拜訪\nart,藝術；美術\nmuseum,博物館\nago,……之前\ncomputer,電腦\nbefore,在……之前；以前\nyesterday,昨天\nsurf the Internet (Net),上網\nminute,分鐘\nhour,小時\nstory,故事\nlazy,懶惰的\neven,甚至\nshould,應該\njust,恰好；剛剛；只是\nwrong,錯誤的\nso,很；那麼\nlater,稍後\nsave,拯救；省下；儲存\nshare,分享\nsnack,點心\nclimb,攀爬\nkid,開玩笑；小孩\nexplain,解釋\nleftovers,剩菜\nhide-and-seek,捉迷藏\nwise,有智慧的\nhunt,打獵\nlearn,學習；得知\nin the end,最後" }, 
                    { unit: "K L6", words: "mountain,山\nlake,湖\nisland,島\nbeach,海灘\nriver,河\nhill,小山；丘陵\npond,池塘\nhike,健行\nswim / swam,游泳\nairport,機場\nbright,明亮的；晴朗的\nguy,傢伙；人\nsuitcase,（旅行用的）手提箱\nthrough,通過；穿過\nbring / brought,帶來\nplastic,塑膠的；塑膠\nkeep / kept,保留；保持\nthrow / threw... away,扔掉……\nstart,開始\nbegin / began,開始\nelementary school,小學\nhate,討厭；憎恨\namazing,令人驚喜的\nlaw,法律\n-free,（用於詞尾）無……的\nkind,種類；友善的\nprogram,計畫\nbuy / bought,買\nhospital,醫院\npackage,包裝；包裹\npoor,貧窮的；可憐的\nstop,停止\ncollect,收集\nhalf,一半（的）；二分之一\nmillion,百萬\nlead / led,領導\none of a kind,獨一無二" },
                    { unit: "U L1", words: "like,喜歡；像\nsport,運動\nmuch,多（的）\nteam,隊；組\npractice,練習\nevery,每一\nthen,那麼\nswim,游泳\njoin,參加\neye,眼睛\nhair,頭髮\nknow,知道；認識\nhundred,百\ncentimeter,公分\nYou can say that again!,一點也沒錯！\nguitar,吉他\npiano,鋼琴\nfly a kite,放風箏\npaint,畫圖；油漆\nmake a cake,做蛋糕\nnose,鼻子\nleg,腿\nlarge,大的\near,耳朵\nmouth,嘴巴\nthick,厚的\nlip,嘴唇\nstrong,強壯的\narm,手臂\nheight,身高；高度\nplayer,選手；球員\nthe USA,美國\nbody,身體\nput one’s all,盡全力\ninto,到…裡面\na lot of,很多的\nstand out,突出\ndifferent,不同的\ntop,頂尖的\non the other hand,另一方面\nmake up for…,彌補…" }, 
                    { unit: "U L2", words: "early,早的\nwork,工作\noften,經常\nget up,起床\nusually,通常\nseldom,很少\nsometimes,有時候\neven,甚至\nlate,晚的\ndo one’s homework,做功課\nhour,小時\nalways,總是\ntired,疲累的\nshower,淋浴\nnever,從未\nby the way,順帶一提\nlibrary,圖書館\ncheck out,借（書）\nonce,一次\ntwice,兩次\nwalk,溜（寵物）\nI can’t help it.,我沒辦法。/我控制不了。\nthen,然後\ntoo,太…\nHow often…?,多常…？\nabout,大約\nbrush one’s teeth,刷牙\nface,臉\nbreakfast,早餐\nlunch,午餐\nexercise,運動\ncomputer,電腦\nminute,分鐘\nanswer,回答；答案\nquestion,問題\ntrouble,困難；麻煩\nlife,生命；生活\nlove,愛\nreal,真實的" },
                    { unit: "U L3", words: "painting,畫作\nflower,花\nwhich,哪一個\nthirsty,口渴的\ncoffee,咖啡\nshop,商店\nlater,稍後；晚點\nOf course.,當然。\nclerk,店員\nmay,可以；可能\njuice,果汁\nwant,想要\nanything,任何事物\nelse,其他\ntreat,請客；款待\nsweet,甜美的；甜的\nhot,熱的\nchocolate,巧克力\ndollar,元\nfor here,內用\nto go,外帶\nHere you are.,給你。\nbright,鮮豔的；明亮的\ndark,黑的；暗的\nart,美術；藝術\nmilk,牛奶\nhamburger,漢堡\nchicken rice,雞肉飯\ntea,茶\nice cream,冰淇淋\nsoup,湯\nsandwich,三明治\nwork,作品\nshow,表現；秀出\npart,部分\nsky,天空\nstreet,街道\nby,被；由" }, 
                    { unit: "U L4", words: "why,為什麼\nwear,戴；穿\nmask,口罩；面具\nbecause,因為\nsick,生病的\nwater,水\nglass,玻璃杯；玻璃\nflour,麵粉\nneed,需要；需求\npie,派\nstill,仍然\nthing,東西；事情\na little,一點點\nsalt,鹽\nsomething,某物；某事\nsugar,糖\nget,取得\nall right,好吧；好的\nso,所以\nback off,退後；走開\nmeal,餐\nbottle,瓶子\ncandy,糖果\npopcorn,爆米花\ncup,杯\nbowl,碗\nfruit salad,水果沙拉\npizza,披薩\nmilk shake,奶昔\ncan,罐子\ntoast,烤土司；烘烤\nbread,麵包\nyummy,好吃的\neasy,容易的\nsnack,點心\nkid,小孩\ncheese,起司\nplate,盤子\nlast,最後（的）\nenjoy,享受；喜愛\nturn into,(使) 變成\neach,每一個 (的)" },
                    { unit: "U L5", words: "yesterday,昨天\nbeach,海灘\ntrash,垃圾\nago,前；以前\nvisit,拜訪\nisland,島嶼\na few,幾個；一些\nsea,海\nstop,停止\nhappen,發生\ndead,死亡的\nwarm,溫暖的\nrainforest,雨林\ndie,死亡\nby,在…旁邊\nHow come?,怎麼會? / 為什麼?\nthen,那時候\nbusy,忙碌的\nriver,河流\nlake,湖泊\nhill,山丘\nmountain,山\ncamp,露營；紮營\nclimb,爬（山）\nrow a boat,划船\nplant,種植；植物\nhike,健行\npicnic,野餐\nlast,上一個的\nlive,居住\nplayground,遊樂場；操場\neverything,每樣事物\nchange,改變\nburn,燃燒\noil,油\nsell,賣\nmake money,賺錢\nmiss,想念\nlittle,小的\nlittle by little,一點一點地；\n逐漸地\nway,方式" }, 
                    { unit: "U L6", words: "airport,機場\ntravel,旅行；行進\nrest,休息\nhotel,飯店\nplane,飛機\nthe sights,風景；名勝\nbookstore,書店\nbuy,購買\njust,就；只\nlearn,學習\nstory,故事\ncool,酷的\ntrain,火車\ncold,冷的\ntry,嘗試\nway,距離；路線\ntake,帶；拿；取\nthe other day,前幾天\nstation,車站；局\ndepartment store,百貨公司\nrestaurant,餐廳\ntheater,電影院\nmarket,市場\ntemple,寺廟\nfamous,有名的\nduring,在…期間\nbesides,除…之外\nfall in love,墜入情網\nage,年紀\nlose,失去\ncry,哭泣\nhide,躲藏\nbuild,建造\ntrip,旅行；行程\nsadly,令人傷心地\nlast,持續" }
                ]
            }
        ]
    },
    {
        grade: "八年級",
        semesters: [
            {
                semester: "114上",
                units: [
                    { unit: "K L1", words: "season,季節\nweather,天氣\nrainy,下雨的\nwet,溼的\nsunny,晴朗的\ncloudy,多雲的；陰天的\nwindy,風大的\nsnowy,下雪的\nspring,春天\nsummer,夏天\nautumn / fall,秋天\nwinter,冬天\nsky,天空\nfeel / felt,感覺\nair,空氣\ncommon,普遍的\ndark,黑暗的；深色的\nforget / forgot,忘記\numbrella,雨傘\nafraid,害怕的\nheavy,大量的；重的\nshower,陣雨；淋浴\nreport,報導；報告\nunder the weather,身體不舒服\nsea level,海平面\ndanger,危險\nfix,解決（問題）；修理\nbuild / built,建造\nfar,遙遠地；遙遠的\nfisherman,漁夫\nbecome / became,變成\ncry,哭泣\nlive,生活；居住\nsafe,安全的\nprotect,保護\nnature,大自然\nabove,在上面；在……上面\nlead / led to,導致" }, 
                    { unit: "K L2", words: "head,頭\nhair,頭髮\nshoulder,肩膀\nstomach,肚子；胃\narm,手臂\nhand,手\nknee,膝蓋\nleg,腿\ntoe,腳趾\nneck,脖子\ncatch / caught a cold,感冒\nfever,發燒\nheadache,頭痛\nsore throat,喉嚨痛\nstay,停留\nmask,口罩；面具\ncall,打電話；呼喊\nspeak / spoke,說話；講\nsend / sent,寄；送\nmessage,訊息\nwhy,為什麼\nbecause,因為\ncountry,國家；鄉間\nserious,嚴重的；認真的\nhealth,健康\nhurt / hurt,疼痛；受傷的\nice cream,冰淇淋\nso,所以\ntoo bad,太糟了\ntreat,治療；對待\nas,如同\nsick,生病的\nmedicine,藥\ncoat,大衣\nhealthy,健康的\nbody,身體\nclothes,衣服\nstrong,強壯的；堅固的\nmaybe,也許\ntry,嘗試\nput on,穿上\nas for,至於" },
                    { unit: "K L3", words: "chicken,雞；雞肉\nant,螞蟻\nugly,醜陋的\nduck,鴨子\ngoose,鵝\nfrog,青蛙\ncow,母牛\nmap,地圖\nbeginning,開頭\nmiddle,中間；中間的\nquarter,十五分鐘；四分之一\nalong,沿著\nclear,晴朗的；清楚的\npass,經過；通過\nforest,森林\ndry,乾燥的；（使）變乾\nsomething,某物；某事\njar,罐子\nbeak,鳥嘴\nreach,達到；伸出手臂（拿）\nrock,岩石；搖動\nfly / flew,飛行；駕駛（飛機）\npick up,撿起\nback,回原處；後面（的）\ndrop,丟下；落下\ninto,到……裡；進入\nGood job!,做得好！\nbe proud of,以……為榮\nback and forth,來回地\nfinally,最後\ntop,頂端；最好的\npast,經過；過去\nfinish,完成；結束\nanything,任何事物\nshout,喊叫\njoy,喜悅\npool,水池；游泳池\nwhen,當……時\nclose,接近地" }, 
                    { unit: "K L4", words: "waiter,男服務生\nwaitress,女服務生\nhousewife,家庭主婦\nmailman (mail carrier),郵差\npolice officer,警察\nsecretary,祕書\nfactory worker,工廠工人\nactor,男演員\nactress,女演員\nreporter,記者\nsinger,歌手\nwriter,作家；作者\nmusic,音樂\nguitar,吉他\ndrum,鼓\nfuture,未來\ninteresting,有趣的\ncamera,攝影機；相機\nimportant,重要的\npopular,受歡迎的\ngift,天分；禮物\ntell / told,講；告訴\nfunny,好笑的；滑稽的\nplan,計畫\nstar,明星；星星\nwithout,沒有\ndream,夢（想）；夢見\nteenager,青少年\nexciting,刺激的；令人興奮的\nfight / fought,對抗；打架\none another,彼此\nmoney,錢\nfamous,有名的\ntrain,訓練；火車\nsadly,令人遺憾地\nteam up with,跟……組隊\nhave to,必須\nstay up,熬夜" },
                    { unit: "K L5", words: "temple,寺廟\nsupermarket,超級市場\nrestaurant,餐廳\nbank,銀行\nchurch,教堂\nbakery,麵包店\nbridge,橋\nhotel,飯店\ndepartment store,百貨公司\nmetro station,捷運站\nbookstore,書店\npost office,郵局\nflower shop,花店\ntrip,旅行\nduring,在……期間\nvacation,假期\nwill / would,將\nown,自己的；擁有\nlocal,當地的\ntour,旅遊行程\nspend / spent,花費（金錢；時間）\nthousand,千\neach,每個（的）\npay / paid,付錢\ntomorrow,明天\nalmost,幾乎\ndecide,決定\ncost / cost,花費（金錢）\nfan,……迷；電扇\nleave for,前往\nvendor,攤販\nquick,迅速的\nstall,攤位\ncareful,小心的\nboat,小船\nsell / sold,賣；出售\nlow,低的；矮的\nprice,價格；代價\nremember,記得\ncash,現金\nwonderful,美好的" }, 
                    { unit: "K L6", words: "airplane (plane),飛機\nbicycle (bike),腳踏車\ntruck,卡車\nscooter,輕型機車\nmotorcycle,重型機車\ntaxi ,計程車\nship,船；艦\nnorth,北方（的）；朝北\nwest,西方（的）；朝西\nsouth,南方（的）；朝南\neast,東方（的）；朝東\ndrive / drove,駕駛（車）\nride / rode,騎（車；馬）；搭乘\nrow,划（船）\nExcuse me.,不好意思。\nsir,先生\nturn left,左轉\ncorner,轉角\nstraight,直地；直的\nblock,街區\nacross from,在……對面\nbottom,底部（的）\nrule,規定\nbroken,破損的\nshake / shook hands,握手\nfavorite,最喜愛的\npocket,口袋\nmonster,怪獸\nclerk,店員\nconvenient,方便的\nmistake,錯誤\nparking space,停車位\nvisitor,訪客\ncheap,便宜的\nbeef,牛肉" },
                    { unit: "U L1", words: "summer vacation,暑假\nweather,天氣\nTaiwan,臺灣\nfun,樂趣；有趣的\nsnow,下雪；雪\nsend,寄；送\npostcard,明信片\nborrow,借（入）\nlend,借（出）\nglove,手套\nkind,親切的；\n有同情心的\nlovely,可愛的；美好的\njacket,夾克\ngive,給予\nhate,討厭\nheavy,厚重的；大量的\nseason,季節\nspring,春天\ncloud,雲\nsun,太陽\nautumn,秋天\nwind,風\nwinter,冬天\nsunny,陽光普照的\nsnowy,有雪的；下雪的\nrainy,有雨的；下雨的\ncloudy,多雲的\nwindy,風大的\ncool,涼爽的\nspeak,講話\nmad,生氣的\nin fact,事實上\nmean,意指\nanother,另一（的）\norder,點餐；訂購\nstrange,奇怪的；陌生的\nsoon,很快地\nRd.,路\nROC,中華民國" }, 
                    { unit: "U L2", words: "club,社團\nmake up one’s mind,下定決心\ninteresting,有趣的\nscience,科學\nsubject,學科；主題\nhear,聽見\nsame,相同的\ncall,打電話；呼叫\ntell,告訴\npull one’s leg,開玩笑\npoor,不佳的；貧窮的\nend,結尾；結束\nwhose,誰的（東西）\ncamera,相機\nmine,我的（東西）\nWhat’s up?,怎麼了？\nwhen,當⋯\nback,返回\nsign up,報名參加\nwrong,錯誤的\nhold on,稍候\nmath,數學\nsoccer,足球\nChinese,中國的；中國人；中文\nhistory,歷史\nviolin,小提琴\nrobot,機器人\nhealth,健康\nPE,體育\nlook for,尋找\nMs.,女士\nengineer,工程師\nlesson,課；課程\ndifficult,困難的\nteach,教導\nown,自己的；擁有\nfinish,完成；結束\nfestival,節慶\nstart,開始\nchoice,選擇\nnot... at all,一點也不⋯\nfree,免費的\nshow,表演；節目\nmiss out,錯過機會" },
                    { unit: "U L3", words: "someone,某人\nbreak,打破；損壞\ndo the dishes,洗碗盤\nhalf,一半；二分之一\npast,經過；過去（的）\nleave,離開\nquarter,十五分鐘；四分之一\nremember,記得\ntake it easy,放輕鬆\ncool down,冷靜一下\nclose,靠近的\nfeed,餵養\npet,寵物\nsweep,掃\nfloor,地板；樓層\nfix,修理；解決\ndrawer,抽屜\nmop,拖地；拖把\nstairs,樓梯\nwipe,擦拭\nwindow,窗戶\ndry, （使）乾燥；乾的\nhang,吊；掛\nclothes,衣服\nmove,搬遷；移動\ncity,城市\ndream,夢；夢想（的）\nalmost,幾乎\nfall asleep,睡著\nscared,害怕的\nproblem,問題\ntip,訣竅\nhowever,然而\nnothing,沒什麼；無事；無物\ncatch,捉；接\nthrough,穿越；從頭到尾\nfinally,終於；最後\nsave,拯救\nterrible,糟糕的；可怕的\nHalloween,萬聖夜\nchildren,兒童（單數為child）\npumpkin,南瓜\ncut out,割出；切出\nmoment,時刻" }, 
                    { unit: "U L4", words: "whope,希望\nfuture,未來（的）\nplan,規劃；計畫\nlawyer,律師\njob,工作\nget butterflies in one’s stomach,感到緊張\nworry,擔心\nkeep,持續；保持\nidea,主意；想法\nright,權利\nput on,穿上\nreporter,記者\ninterview,採訪；面試\nmail carrier,郵差\ndentist,牙醫\nfactory,工廠\nfisherman,漁夫\nsecretary,祕書\nboss,老闆\nsalesman,銷售員；業務員\nfarmer,農夫\ngrow,種植；成長\nsoldier,士兵\ncountry,國家\ntruck driver,卡車司機\ndrive,開（車）\nsuccessful,成功的\nfind,找到；發現\ngrade,年級\ndecide,決定\nbecome,成為\nrelative,親戚\nbelieve,相信\nact,表演\nall over,遍及\nmake fun of,取笑\ngive up,放棄" },
                    { unit: "U L5", words: "metro,捷運\nlost,迷路的\nmap,地圖\nask,請求；詢問\nExcuse me.,（對不起）請問⋯。\nstraight,直地；直的\nturn left,向左轉\nalong,沿著\nblock,街區\ncorner,轉角；角落\nacross from,在⋯的對面\nsupermarket,超市\nground,地面\nsir,先生\non foot,步行\ntake,搭乘（交通工具）\nby,搭乘；藉由⋯方式\nget off,下（車、飛機等）\nget,到達\nright,右邊（的）\nship,輪船\ntaxi,計程車\nbike,單車\nmotorcycle,機車；摩托車\nscooter,機車\nbank,銀行；河岸\nfire station,消防局\ntoy,玩具\npost office,郵局\nhospital,醫院\npool,水池\ngo jogging,慢跑\ngo sailing,玩帆船；航行\ngo surfing,衝浪\nfly,飛行；駕駛\nbus stop,公車站\ngo biking,騎單車\ngo shopping,購物\nhit,碰撞；打擊\nsound,聲音\nbell,鐘；鈴\nexperience,經歷；經驗\nwonderful,美好的\nplay,戲劇\naround,大約" }, 
                    { unit: "U L6", words: "will,將\nugly,醜的\nsweater,毛衣\ntonight,今晚\nfunny,滑稽的\ncost,價錢為；花費\nprice,價格\nspend,花費（時間、金錢）\nexpensive,昂貴的\non sale,特價中\npair,（一）雙；（一）對\ntotal,總計（的）；全部（的）\npay,付費；工資\nthousand,千\ntomorrow,明天\nhigh,高的\nsave,節省\nwould like,想要\nchange,找零\ntake,花費（時間）\ndress,打扮；洋裝\ncap,（前有遮簷的）帽子\nshirt,襯衫\nbelt,腰帶\njeans,牛仔褲\nsock,襪子\ntie,領帶\npants,長褲\nshoe,鞋\nT-shirt,T恤\nshorts,短褲\nhat,帽子\ncoat,外套\nskirt,裙子\nglasses,眼鏡\nring,戒指；環（狀物）\ntake off,脫下\nfast,快的；快地\nlow,低的\ncheap,便宜的\nwhat’s more,而且\nmost,大部分的\nhurt,傷害\ncome off,從⋯脫落\nsecond,秒" }
                ]
            },
            {
                semester: "114下",
                units: [
                    { unit: "K L1", words: "dress,洋裝\non sale,特價\nshirt,襯衫\nshorts,短褲\njeans,牛仔褲\nsweater,毛衣\njacket,夾克\nskirt,裙子\nring,戒指\nsock,襪子\ncap,（有帽舌的）帽子\ntie,領帶\nbelt,腰帶\npants,長褲\nwallet,錢包\na pair of,一件（褲子）；一雙（鞋）\nglove,手套\ntry on,試穿\ntake / took off,脫下\nbe full of,充滿\nfashionable,流行的；時尚的\nas… as…,如同……一樣地……\nthan,比；比較\nalready,已經\nfashion,流行；時尚\nmedium,中等尺寸；中等的\nfitting room,試衣間\nagree,同意\ncomfortable,舒服的\nlight,輕薄的\nrecycle,回收\nplanet,星球\nbusiness,公司；生意\ncustomer,顧客\nactually,實際上\nowner ,所有人\nitem,項目\nfresh,新鮮的\nmean / meant,意指\nEarth,地球\nturn… into…,（使）成為……" }, 
                    { unit: "K L2", words: "sofa,沙發\nlamp,燈\npiano,鋼琴\nradio,收音機\nwashing machine,洗衣機\nrefrigerator (fridge),冰箱\nviolin,小提琴\nbow,（弦樂器的）琴弓\ntape,膠帶\nconcert,演唱會；音樂會\nturn on,打開（電器）\nturn off,關上（電器）\nscreen,螢幕\npower bank,行動電源\nout of order,故障的\nsweet,甜的；甜蜜的\nmost,最；最多的\nenvelope,信封\nused to,過去經常\nuseful,有用的\nfake,假的\ndeal,交易\nscam,詐騙\nstrange,奇怪的；陌生的\njoke,玩笑；笑話\nseller,賣家\nanymore,再也（不……）\nstop by,順道拜訪\npick up,取（某物）\ntrick,欺騙；騙局\nbillion,十億\npart,部分\ntip,提示；指導\nsecret,祕密（的）\nword,字\nsentence,句子\ninformation,資料；消息\nstranger,陌生人\ntell / told... from...,區分⋯⋯與⋯⋯\nstay,保持" },
                    { unit: "K L3", words: "salad,沙拉\nhamburger (burger),漢堡\ncoffee,咖啡\nsteak,牛排\nFrench fries,薯條\nfried chicken,炸雞\nham,火腿\ncheese,起司；乳酪\npork,豬肉\nbean soup,豆子湯\nvegetable,蔬菜\npizza,披薩\nbun,小圓麵包\ntoast,烤麵包片\nmeat,肉\nbread,麵包\nwall,牆壁\nmeal,一餐\noil,油；石油\nsound,聽起來；聲音\nweight,體重；重量\nsmell,聞起來；氣味\ntaste,嘗起來；味道\ndig / dug in,開始吃\nsoon,很快地\norder,點餐；訂購\nput / put on,增加（體重）\nget / got,變得\nnotice,注意；看到\ninvite,邀請\nbesides,此外；而且\nprobably,也許\nbite,一口的量；咬\nstand / stood for,代表\nmatter,有關係\nsign,招牌；標誌\nfriendly,（某處）令人愉快的" }, 
                    { unit: "K L4", words: "set / set up,搭（帳篷）；建立\nmake / made a fire,生火\nboil,煮沸\nbug,蟲\npicnic,野餐\nhang / hung out,晾（掛）\ntowel,毛巾\nlie / lay,躺下\ngrass,草地；草\nstring lights,繩燈\nmoon,月亮\ncount,數數；計算\npack,打包\nperfect,完美的\nbe able to,能夠\nwell,很好地\nloudly,大聲地\nslowly,緩慢地\ngently,輕柔地\nsmile,微笑\nhop,單腳跳躍\ndancing queen,舞后\nhard,努力地\ntrip,絆倒\nexperience,經歷\ndiary,日記\narrive,抵達\narea,區域；地區\nsuccessfully,成功地\npot,鍋子；壺\nburn,燒焦；燃燒\nunhappy,不開心的\nhold / held,舉辦；握住\ncircle,圓圈\nshy,害羞的\nline,列；線條\nlaugh,笑\nanyone (anybody),任何人\nelse,其他\nclap,拍手；鼓掌\ncheer,欢呼；鼓舞\nfestival,節慶；節日\nheart,愛心；內心\nshape,形狀\nlucky,幸運的" },
                    { unit: "K L5", words: "earthquake,地震\ncover,遮蓋；遮蔽\ntyphoon,颱風\ncandle,蠟燭\nsmoke alarm,煙霧警報器\nelevator,電梯\nraise,舉起；增加\npull,拉；抽出\npush,推；按\nrich,富有的；豐富的\ndeep,深的\nhold / held on,紧紧抓牢；坚持下去\nabroad,在國外\ndangerous,危險的\nmoment,時刻\nhear / heard,聽到\nsomeone (somebody),某人\nscary,嚇人的\nfall / fell off,（從⋯⋯）掉下\ncut / cut,割傷；切\nnothing,沒有事情；沒有東西\nscene,場景\nleading,主要的\nreal-life,真實生活中的\never,在任何時候\ngo / went out,（燈、火）熄滅\nlesson,教訓；（一節）課\nland,陸地；降落\nseveral,數個的\ngrow / grew,成長；增加\ngray,灰色的；灰色\ndozen,一打\nscared,感到害怕的\nwindow,窗戶\nsight,景象\nsurprise,驚訝；使……驚訝\nflood,淹沒；洪水\napartment,公寓\nexcept,除了……之外\ncookie,餅乾\ndrawer,抽屜\nquite,相當地\nangry,生氣的\nfool,傻瓜；愚弄" }, 
                    { unit: "K L6", words: "straw,吸管；稻草\ncarry,攜帶\nmetal,金屬\nspoon,湯匙\nchopsticks,筷子\npaper,紙\nstair,樓梯\ninstead,作為……替代\njog,慢跑\nnewspaper,報紙\npostcard,明信片\nbusinessman,商人\nworkbook,習作\nbother,費心\nend up,最後成為\nocean,海洋\nturtle,海龜；龜\nperhaps,也許\nif,如果\ntake / took action,採取行動\nthough / although,雖然\nbreak / broke down,分解\ncorrect,正確的；更正\nfeed / fed,餵\nbaby,幼鳥；嬰兒\njellyfish,水母\ndie,死亡\ncrazy about,非常喜歡……\nservice,服務\nexcellent,優秀的\nwish,願望；希望\ngarbage,垃圾\nsomewhere,在某處\nenter,進入；輸入\nknife,刀子\nfork,叉子\nchoice,選擇\npossible,可能的\nno longer,不再\ngladly,樂意地" },
                    { unit: "U L1", words: "foreign,外國的\nthan,比\nfriendly,友善的\nconvenient,便利的\npork,豬肉\nbeef,牛肉\ndelicious,美味的\nfeel,感到\nsteak,牛排；肉排\nmenu,菜單\nwaitress,女服務生\nham,火腿\nbutter,奶油\nmedium,五分熟；中等的\nmeat,肉\nsmell,聞起來；氣味\ntaste,嚐起來；味道\nas... as...,如同…一樣…\nget around,各處旅行\ndish,菜餚\nmore,更…\nget,變成\nsound,聽起來\ntop,頂部（的)\nfries/French fries,薯條\nknife,刀子\nfork,叉子\nnoodle,麵\nchopsticks,筷子\nspoon,湯匙\nfried chicken,炸雞\nwaiter,男服務生\nstrawberry,草莓\nbun,小圓麵包\nearth,地球\nbring,帶來；攜帶\nsmile,微笑\nland,陸地；落地\nrock,岩石\nshape,形狀\nclear,晴朗的；清楚的\ncomfortable,舒適的；自在的\nfill,充滿；裝滿\npack,打包；塞進" }, 
                    { unit: "U L2", words: "grass,草地\nred fire ant,紅火蟻\ndangerous,危險的\nbite,咬；咬傷\ndeath,死亡\nkick,踢\nthemselves,他們自己\nkill,殺死\nstay away from...,遠離…\nagree,同意\ncircle,圓圈；畫圈\nmyself,我自己\nsnake,蛇\nwet,潮濕的\nscary,令人害怕的\ndeep,深的\ntrue,真實的\nmost,最…；最多的\ngive... a hand,幫助…\nspider,蜘蛛\ngram,公克\ninsect,昆蟲\nbee,蜜蜂\ninch,吋\nwide,寬的\nkilogram,公斤\nnature,大自然\nbelow,在…之下；在下面\nsea level,海平面\nmile,英里\nfeet,英尺\nsmart,聰明的\ntraffic,交通；車流（量）\nappear,似乎\nair,空中；空氣\nfar,遠\nslow,放慢；慢的；慢地\nlight,燈；光；點亮\ncross,穿越" },
                    { unit: "U L3", words: "loudly,大聲地\nhard,努力地；困難的\nwell,好地\nshare,分享\nweak,虛弱的\nhen,母雞\ndirty,髒的\nbow,鞠躬\nwithout,沒有；無\nquickly,快地\nweb page,網頁\nservice,服務\nwise,明智的\ncheer,歡呼\ncelebrate,慶祝\nmean,刻薄的；兇惡的\nmake,要…做…；使…\nbreak,休息\nover,超過\ntreat,對待\nhave,使…\ngrape,葡萄\ngoose,鵝\nduck,鴨\ngoat,山羊\nsheep,綿羊\npeach,桃子\nturtle,烏龜\npear,梨子\npapaya,木瓜\nvegetable,蔬菜\nguava,芭樂\ntomato,番茄\nwatermelon,西瓜\nAmerican,美國人\nmillion,百萬\npound,磅\npick,採摘；撿拾\nbean,豆\ncent,美分\nchance,機會\nchoose,選擇" }, 
                    { unit: "U L4", words: "typhoon,颱風\nblow,吹\nrose,玫瑰花\nbalcony,陽台\nmust,必須；一定\nprepare,準備\nshould,應該\ncandle,蠟燭\nradio,收音機\nnews,新聞；消息\nif,如果\nor,否則\nhave to,必須\ngo out,熄滅\ntrain,訓練\nface,面對\ntry one's best,盡力而為\nturn on,打開（電源）\nlatest,最新的\nstar,星星\nshine,閃耀；照耀\ngiant,巨大的\nwave,浪\nrainbow,彩虹\npretty,漂亮的\ngarden,花園\nfrog,青蛙\nnoise,聲響；噪音\npond,池塘\nnoisy,嘈雜的\nearthquake,地震\nbravely,勇敢地\nsharp,尖銳的\nreach,到達\nspace,空間\nsize,大小；尺寸\nas,作為；如同\ntimes,倍" },
                    { unit: "U L5", words: "although,雖然\nmatter,問題；事件\nsore throat,喉嚨痛\nexplain,解釋\ncough,咳嗽\nprobably,很可能；大概\ntake care of,照顧\nnoon,中午\nboth,兩者（都）\nmedicine,藥\nhoney,蜂蜜\nlemon,檸檬\nuseful,有用的\nstand,攤位\nfeel like,想要\ncold,感冒\nwell,健康的\ntreat,治療\nhead,頭\nheadache,頭痛\nstomachache,胃痛\nfever,發燒\nrunny nose,流鼻水\nknee,膝蓋\nnail,指甲\nfinger,手指\nneck,脖子\nshoulder,肩膀\nbakery,麵包店\ncommon,常見的；共同的\nactually,實際上；事實上\nhelpful,有幫助的\nroot,根；根源\nreason,原因；理由\npower up,增強力量\nsweet,甜食\nsharp,敏銳的" }, 
                    { unit: "U L6", words: "pass,傳遞；通過\nthrow,丟；投擲\npoint,得分\nwin,贏；獲勝\nuntil,直到\nmember,成員\ngroup,團體\nfail,考不及格；失敗\ntest,考試\nafraid,害怕的；擔憂的\nforget,忘記\nfresh,新的；新鮮的\ncount... in,算…參加一份\nbegin,開始\nmeeting,會議；會面\ncome on,快點；少來了\nexcuse,藉口；理由\naround the corner,即將來臨；在附近\ngrade,成績\nhold back,阻礙\nfew,很少（的）\nsimple,簡單的\nexpect,預計；期望\nmistake,錯誤\nangle,立場；角度\nallow,允許\nlaugh,笑；笑聲\nkeep in mind,記住\nhonest,誠實的；可信的\nlead to,導致\npush,迫使；推動\nexcellent,優秀的；極佳的\nbe able to,能夠\ndefine,下定義；界定\nmatter,要緊；重要\npicture,想像\nas for,至於\nto the full,盡可能" }
                ]
            }
        ]
    },
    {
        grade: "九年級",
        semesters: [
            {
                semester: "114上",
                units: [
                    { unit: "K L1", words: "subject ,學科\ntopic,主題\nhairdryer / hair dryer,吹風機\npaper ,紙\ncentury ,世紀\ncommon,普遍的\narea,地區；區域\nfreeze / froze ,凍結；結冰\npotato,馬鈴薯\nstick ,枝條\nAmerican,美國的；美國人\nsoldier ,士兵；軍人\nmain ,主要的\nlanguage ,語言\nsince,自……以來\ncelebrate ,慶祝\nnational ,國家的；國立的\nthick,粗的；厚的\nexcellent,優秀的\ntype,種類\nfry,油炸；油煎 \nholiday,節日；假期\nsnack ,點心\nEaster ,復活節\nchocolate ,巧克力\nHalloween,萬聖節前夕\ncandy ,糖果\nThanksgiving ,感恩節\npumpkin ,南瓜\nbake ,烘烤\ncookie ,餅乾\nChristmas Eve,聖誕節前夕；平安夜\nnobody,沒有人\nwave ,揮（手）\nsuccessful ,成功的\nisland ,島\nyet ,還（沒）；尚（未）\ninch ,英寸\nking ,國王；王者" }, 
                    { unit: "K L2", words: "delivery,運送\napp,應用程式\namong,在……中\nage,年齡\nchart,圖表\ninterested,感興趣的\nseveral,幾個的；數個的\nreason,原因\nhelpful,有用的\ntired,疲勞的\nservice,服務\nsuch as,例如；像\nchoice,選擇\ndriver,駕駛；司機\nuniform,制服\nnews,消息；新聞\nexcited,感到興奮的\nboring,無聊的；無趣的\nbored,感到厭煩的\nscared,感到害怕的\ntiring,令人疲倦的\nsurprising,令人驚訝的\ntip,給……小費；小費\nsurprised,感到驚訝的\ncouch,沙發\ninterest,興趣；使……感興趣\nmind,介意\nchance,機會\ndownload,下載\ndiscount,折扣\nsurprise,驚喜；使……驚訝\nlist,清單\nat least,至少\nangry,生氣的\nlocation,位置\ntap,輕觸" },
                    { unit: "K L3", words: "spider,蜘蛛\nraise,引起；養育\ngender,性別\nstereotype,成見；刻板印象\nweak,虛弱的\nhelpless,無助的\nvalue,價值\nengineer,工程師\nlawyer,律師\npowerful,有力量的；強大的\npower,力量\nhonest,誠實的\nmodern,現代的\nlimited,有限的\npresent,展現；禮物\nlovely,討人喜歡的；漂亮的\nborn,出生的；誕生的\npretty,漂亮的\nbrave,勇敢的\nexpect,期待；預計\nblow / blew... away,使……大為驚訝\nbe filled with,充滿\ngarbage,垃圾\nheart,心；感情\nthank goodness,謝天謝地\nhope,希望\nexcept,除了……之外\nquite,相當地\nstupid,愚蠢的；笨的\nending,（故事的）結局\nugly,醜陋的\nhate,討厭；憎恨\nallow,允許\nopinion,意見\ncouldn’t help but...,忍不住……\nput oneself in someone’s shoes,設身處地以……的立場想" }, 
                    { unit: "K L4", words: "create,創造\ndictionary,字典\ncase,實例\ncombine,結合；合併\nform,形成\npleasure,樂趣；榮幸\nairport,機場\nbuild / built,建造\nnotebook (computer),筆記型電腦\ne-mail,電子郵件\nby accident,意外地\nlip,嘴唇\nwhether,是否\ndefine,定義\nexplain,解釋；說明\nbutterfly,蝴蝶\ninterview,面試；採訪\nfrog,青蛙\nsalesman,銷售員\nmad,惱火的\nhen,母雞\nblind,瞎的；盲的\nbat,蝙蝠\nglasses,眼鏡\nlie ,說謊\nfarm,農場\nsentence,句子\nglad,高興的\ntrouble,麻煩\npain,疼痛；痛苦\nmeaning,意思；意義\nprayer,祈禱者\nlesson,（一節）課；經驗；教訓" },
                    { unit: "K L5", words: "foreign,外國的\nlollipop,棒棒糖\npink   ,粉紅色（的）\npurple,紫色（的）\nnatural,天然的\npackage,包裝； 包裹\ncompany,公司\nmillion,百萬\ncenter,中心；中央\nboss,老闆\namazing,令人驚喜的\nmarried,已婚的\n-sounding,聽起來……的\nhave a sweet tooth,愛吃甜食\nrise,上漲；升高\nsuccess,成功\nmark,目標；標記\nbelong to,屬於\ngrown-up,大人；成年人\nwise,有智慧的\nhard-working,勤勉的\nleader,領導者\nsimple,單純的；簡單的\nrepeat,重複；複誦\ninformation,資料；消息\ndentist,牙醫\nknowledge,知識\nfail,失敗；不及格\ndeal with,處理\nfulfill,執行；實踐\npopcorn,爆米花\nschool fair,園遊會\ntool,工具\npop,爆開\nburn,燒焦；燃燒\npot,鍋子；壺" }, 
                    { unit: "K L6", words: "appear,似乎；出現\npromotion,促銷\nfool,愚弄；傻瓜\ntrick,騙局\nunderstand,了解\nsecret,祕密（的）\nprofit,利潤\nbelow,在下面；在……的下面；低於\ncheat,欺騙；作弊\nwallet,錢包\nwaste,浪費； 廢棄物\ndeal,交易\nkilogram,公斤\ngram,公克\npound,磅\npeach,桃子\npear,梨子\nlemon,檸檬\ntomato,番茄\npin,大頭針；別針\nsuperglue,三秒膠\npaste,漿糊；黏貼\njump rope,跳繩\nmarker,麥克筆\ngray,灰色（的）\npaint,顏料；油漆；（用顏料）畫\ntotal,總數（的）\nproduct,產品\npass up,放過；錯過（機會）\nsample,樣品\nbottom,底部（的）\nlevel,高度；程度\ncent,分（金錢單位）\nabove,高於；在……的上面；在上面\ncentimeter,公分\nheight,高度\ntherefore,因此\nshopkeeper,店主\ncome to think of it,這樣一想\nsight,所見之物；景象" },
                    { unit: "U L1", words: "yet,還（沒）\nalready,已經\ndiet,節食；飲食\nsince,自從\nphoto,照片\ncrazy,荒唐的；瘋狂的\nas…as possible,盡可能的⋯\nslim,苗條的；微小的\ntip,訣竅\ntype,類型\never,曾經\nhabit,習慣\ntake action,採取行動\nbe all ears,洗耳恭聽\nat least,至少\nYou got it.,沒錯。\nchoice,選擇\ngym,健身房；體育館\nabroad,到國外\ncheat,作弊；欺騙\ncopy,抄襲；複製\nrace,速度競賽\nstay in shape,保持健康\nletter,信\nteenager,青少年\nsenior high school,高中\nunderstand,瞭解\ndrum,鼓\njoy,樂趣；喜悅\npop,流行音樂\nlately,最近\nangry,生氣的\nserious,嚴重的\ninterest,興趣；使感興趣\ngarbage,垃圾\nunhappy,不快樂的\nwish,祝福\nenvelope,信封\nstamp,郵票\nstar,明星\ncall,稱呼\ntalk…into,說服（某人）做⋯" }, 
                    { unit: "U L2", words: "actor,演員\nact,表演\ntouch,觸動；碰觸\nheart,心；心臟\nsurprise,（使）驚訝\nbored,感到無聊的\nhard-working,勤奮的\nguess,猜測\nseveral,幾個的\nsurprised,感到驚訝的\nexciting,令人興奮的；刺激的\nghost,鬼\ncastle,城堡\nsurprising,令人驚訝的\ninterested,感興趣的\nboring,無聊的\ndownload,下載\nInternet (=Net),網路\nset,建立；樹立\nexcited,感到興奮的\nticket,票\nonline,在網上；線上的\nproud,自豪的；驕傲的\nI’ll pass.,不用了。\nbook,預訂；預約\nactress,女演員\ntowel,毛巾\ncomb,梳子；梳理\nbat,蝙蝠\nlie,謊言；說謊\nfake,假的；偽造的\nnewspaper,報紙\nnobody ,無人\nanybody (=anyone),任何人\npiece,（一）則；片；張\ndig,挖掘；尋找\nsentence,句子\nspell,拼字\ntrick,騙；詭計\npost,貼文；張貼\nright away,立刻；馬上\nhit,點擊數" },
                    { unit: "U L3", words: "senior center,樂齡中心\npleasure,愉快；榮幸\nattack,攻擊\ntoe,腳趾\ndrop,（使）落下；丟下\nland,落地；陸地\npuppy,幼犬\ntraffic,車流（量）；交通\nmiddle,中間\ncarry,攜帶\nnote,紙條\npocket,口袋\npray,祈求；祈禱\nblow up,爆炸\nin time,及時\narea,區域\nglue,膠水\npaste,黏貼\nyard,庭院\npipe,水管\nbench,長凳；長椅\nbadminton,羽毛球\ntennis,網球\nslide,滑梯\nseesaw,翹翹板\nswing,鞦韆\ntool,工具\npot,盆；鍋\nseed,種子\nbake,烘焙\nfan,風扇\nfill,裝滿\nbasket,籃子\nstranger,陌生人\nboil,煮沸\nsmile,微笑\npack,（一）包；副\nknock,敲\nshow up,出現\nhand,遞給" }, 
                    { unit: "U L4", words: "gate,大門\nfile,檔案\nquiz,小考\nblackboard,黑板\nchalk,粉筆\nscreen,螢幕\nerror,錯誤\nbutton,按鈕；鈕扣\nenter,輸入；進入\nwake word,喚醒字詞\nwhether,是否\nlist,清單；列出\nhoney,親愛的（用於稱呼）\nsave,儲存\nthrough,透過；憑藉\nif,是否\nnot... anymore,不再…\nvoice assistant,語音助理\nmachine,機器\ndozen,（一）打\nrefrigerator (=fridge),冰箱\nupload,上傳\ne-mail,電子郵件\nkey,鑰匙\nthe cloud,雲端\ntype,打字\nshopkeeper,店主\ncellphone,手機\ncollect,收集\noutside,在外面；外面（的）\nwallet,錢包\ncouch,沙發\nlamp,檯燈\nprogram,節目\nmodern,現代的\ncross that bridge when one comes to\nit,船到橋頭自然直；到時候再說\nstand for,代表\nset,設定\nshape,塑造" },
                    { unit: "U L5", words: "arrive,抵達\nplanet,行星\nline,隊伍；直線\nappear,出現\nrestroom,洗手間\nbath,沐浴\nuniform,制服\ntail,尾巴\nbottom,臀部；底部\nmain,主要的\nnotice,注意到；告示\nbelong,屬於\ngo on,發生\nlead,通往\nplay,扮演\nsquare,正方形的；正方形\nstring,串；線\nround,圓形的\ndot,圓點\nbow,蝴蝶結\npin,飾針；胸針\nneighbor,鄰居\nforeigner,外國人\nhobby,嗜好\nbusinessman,商人\nbusiness,生意；事業\ndictionary,字典\nworkbook,作業本\nlight,輕的\nexercise,習題；練習\nborn,出生的\nprize,獎\ntopic,主題\nknowledge,知識\npublic,公眾（的）\nbe no stranger to,對…不陌生\nkey,關鍵（的）" }, 
                    { unit: "U L6", words: "apartment,公寓\nglad,高興的\ntown,城鎮\npolite,有禮貌的\nseat,座位\nbeside,在…旁邊\nexcept,除了\nblank,空白（的）\npresent,禮物\ninvite,邀請\nperhaps,或許\nkiss,吻\nside,側面；邊\nsidewalk,人行道\nused to,過去時常…\nappear,似乎\nserious,認真的\nblind,盲的\nApril Fools' Day,愚人節\ntape,用膠帶黏貼；膠帶\npaper,紙\njoke,玩笑；笑話\nvisitor,遊客；參觀者\nsomewhere,在某處\nmud,泥土\nahead,在前方\nheat,高溫；加熱\nrise,升起；起身\nrich,富有的\nlazy,懶惰的；慵懶的\nhave bigger fish to fry,有更重要的事要做\nsmoke,煙霧；抽菸\ncover,覆蓋；遮蓋（物）\nlie,躺；臥\ndraw,提取（水、錢）\nspell,咒語" }
                ]
            },
            {
                semester: "114下",
                units: [
                    { unit: "K L1", words: "attack,攻擊\nforeigner,外國人\nsharp,鋒利的\nfake,假的\nwhile,當……時\nlazy,懶惰的\nbee,蜜蜂\nhoney,蜂蜜\nas soon as,一……就……\nas long as,只要……就……\nbridge,橋\ntyphoon,颱風\ngiant,巨大的\nkite,風箏\nchalk,粉筆\nbug,蟲\ninsect,昆蟲\nChina,中國\nbalcony,陽臺\nneighbor,鄰居\ yard,院子\nant,螞蟻\nbench,長椅；替補隊員席\nspot,看出\nsource,資訊來源\ntrusted,可信的；可靠的\nwebsite,網站\nerror,錯誤\ncopy,複製；複本\nheadline,標題\nsmoke,抽菸；煙\ntruth,真相\nangle,觀點；角度\nfar,遙遠的；遙遠地\nover-the-top,太過頭的\ntip,提示；指導" }, 
                    { unit: "K L2", words: "widely,廣泛地\nneither,也不；兩者皆非\nmember,成員；會員\njoy,喜悅\nrelative,親戚；親屬\npolite,禮貌的\nlonely,孤獨的\nhobby,嗜好\nfeeling,情感；感情\nshy,害羞的\nstranger,陌生人\nneither…nor…,既不……也不……\nput down,貶低\ntidy,整理；收拾；整齊的\nroll,翻滾；滾動\nhunt,搜尋；打獵\ntraffic,交通\nlend,借（出）\nborrow,借（入）\nGod,上帝；神\numbrella,雨傘\nmud,土；泥土\ntowel,毛巾\ngo ahead,（用於給別人許可）開始；做\nbe all ears,洗耳恭聽\nturn,（依次輪到的）機會\neither…or…,不是……就是……" },
                    { unit: "K L3", words: "pool,游泳池；水池\nwish,希望；願望\nhuman,人類的；人類\nrisk,風險\nhopefully,但願\nnail,釘子；指甲\nbell,鈴\nblank,空白的；空格\nblackboard,黑板\nenvelop,信封\nstamp,郵票\npostcard,明信片\nmask,面具；口罩\nring,戒指\ncomb,梳子；梳\ntie,領帶\ndot,點\nmatch,相配\nbelt,腰帶\ngas,汽油\npipe,管子\ndrum,鼓\nviolin,小提琴\nbow,（弦樂器的）琴弓\npiano,鋼琴" }, 
                    { unit: "K L4", words: "yearbook,畢業紀念冊\nneck,脖子\nprize,獎；獎金\nquiz,小考\nworkbook,習作\nnotes,筆記\nforever,永遠\ncow,母牛\ngoose,鵝\nduck,鴨子\nkick,踢\ntail,尾巴\nslim down,變瘦\nprogram,計畫\nmile,英里\nplant,植物；種植\nrose,玫瑰\nseed,種子\ncircle,圓圈\ndeath,死亡\nghost,鬼\nband,樂團\nsquare,廣場；正方形（的）\nhandsome,英俊的\nknock... down,擊倒\nsail,航程；航行\nrainbow,彩虹\nhill,小山；丘陵\nshoulder,肩膀\nroot,根；根源\nput up with,忍受" },
                    { unit: "U L1", words: "either,也（不）\nnorth,向北地；北方（的）\nsouth,向南地；南方（的）\neast,向東地；東方（的）\nwest,向西地；西方（的）\nget married,結婚\nneither,也不\nshy,害羞的\nlonely,寂寞的；孤獨的\ndeal,約定；交易\ndate,約會\ncheer up,振作起來\neven though,即使\nhead,朝…行進\nkeep in touch,保持聯繫\nclass leader,班長\nqueen,皇后\nnational,國家的\nrow,（一）排；行；列\ngrade,年級\nmiss,趕不上；錯過\nhot spring,溫泉\nquite,相當\ncorrect,更正；正確的\npower,力量\nby,早於；不遲於\nas soon as,一…就\ncourse,課程；路線\npart-time,兼職的\ntest the water,試探\nact on,執行；落實" }, 
                    { unit: "U L2", words: "blanket,毯子\nneither…nor…,既不…也不…\nstupid,愚蠢的\neither…or…,不是…就是…\nhave nothing to do with…,和…無關\nmind,介意\nstudy,研究\nnot only… but also…,不但…也…\nsign,跡象\npark,停車\nstay up,熬夜\ncountry,鄉村\nsight,視線；景象\nleave,遺留\ntidy,整齊的；整理\nitem,品項\nrepeat,重複\npackage,包裹\nlanguage,語言\nwave,揮手；揮舞\nto put it simply,簡單地說\nstore,儲藏\nletter,字母\nset,（一）套；組；副\nyard,碼\ncount on,依靠；指望" },
                    { unit: "U L3", words: "while,當…時\npoint out,指出\nplease,（使）滿意；\n取悅\ncase,案例\npoint,意義；論點" }, 
                    { unit: "U L4", words: "vote,投票\nelection,選舉\ncheck in,報到\nleave for,前往\nstamp,印章；蓋章\nfollowing,以下（的）\nraise,舉起；提高\ndeal with,處理；負責" }
                ]
            }
        ]
    }
];